### ISSUE TITLE
Composer Package PHP7.1

### ISSUE THREAD

**Issue by juhanix** [Ethan3600/EthanYehuda_CronjobManager#10]
`Could not find package ethanyehuda/magento2-cronjobmanager at any version matching your PHP version 7.1.11.0`
Newest extension version (1.1.0) php: ~5.6.5|7.0.2|7.0.4|~7.0.6
Can you support PHP version 7.1?

Cheers,
Juhani

**Comment by Ethan3600** [comment]
Hi @juhanix, thanks for reporting this issue!

I added support for PHP v7.1 on composer.json in the new releases:

**v1.1.1** and **v0.2.1**
