### ISSUE TITLE
Schedule source model is not used in grid

### ISSUE THREAD

**Issue by schmengler** [Ethan3600/EthanYehuda_CronjobManager#105]
**Describe the bug**
The job filter in the schedule grid is has the type "text". The existing source model can be used to have a dropdown filter

**To Reproduce**
1. Go to 'Cron Job Manager'
2. Click on 'Filters'

**Expected behavior**
Filter by job code shows a dropdown of all jobs

**Additional context**
This may be debatable. Selecting jobs from a dropdown is convenient, but it removes the possibilty to search for multiple jobs by prefix

**Comment by Ethan3600** [comment]
I suppose this is somewhat subjective, but I suppose we can't expect an system admin to know every single cron job code. Better to be explicit and provide all options in the dropdown.
