### ISSUE TITLE
Colorize status columns

### ISSUE THREAD

**Issue by schmengler** [Ethan3600/EthanYehuda_CronjobManager#107]
**Is your feature request related to a problem? Please describe.**
I want to see quickly which jobs have an error or working status

**Describe the solution you'd like**
Colorize the status column:
- Pending: gray
- Running: yellow
- Success: green
- Missed: ? (something less drastic than red, maybe orange or black)
- Error: red
- Killed: red

**Additional context**
Example of colorized columns from the cache management:
![image](https://user-images.githubusercontent.com/367320/52554173-41bacd00-2de6-11e9-9a15-03b408848bcd.png)

**Comment by Ethan3600** [comment]
This was implemented in v1.8.1!

Let me know if there are any issues. Closing for now.
