### ISSUE TITLE
Drop PHP 7.0 compatibility

### ISSUE THREAD

**Issue by schmengler** [Ethan3600/EthanYehuda_CronjobManager#110]
**Is your feature request related to a problem? Please describe.**
PHP 7.0 has reached end of life December 2018 and we should not need to support it any longer

**Describe the solution you'd like**
Remove PHP 7.0 from the build matrix and allow language features from PHP 7.1 like nullable types and constant visibility.

This can be done with a 1.8.0 or 2.0.0 release, depends how conservative our definition of backwards compatibility should be.

**Comment by Ethan3600** [comment]
Let's drop it. Going to push this for 1.8.0 release.

See commit: https://github.com/Ethan3600/magento2-CronjobManager/commit/f26feaaa89995eb900218040cb7eaa1f5472bd72
