### ISSUE TITLE
Add Archive Cron Job

### ISSUE THREAD

**Issue by gamort** [Ethan3600/EthanYehuda_CronjobManager#119]
Maintaining a reasonable history view of 3 days of both success and error[how else can you check to see if something has spiked/started to cause problems] will fill up the cron schedule table and make it unusable.

Having an ARCHIVE of cron jobs instead, a duplicate table to record all cron jobs removed from the main table, would provide this history without breaking cron.

The initial implementation does not even need to provide a UI beyond setting time limits for how long to maintain archived data.   Just keeping a table of the history allows command line lookup and future releases could look into providing a ui.

**Comment by Ethan3600** [comment]
In theory (I say that in a "hand wavy" way) you can just extend the "History lifetimes" for each cron job. I'm not sure a whole table is really something we need to view historical data on cron jobs.

Moreover, we shouldn't make an additional table b/c Magento's Cron system sucks. Yes, it's buggy.. but, new solutions shouldn't revolve around workarounds for open source software bugs.

That aside, I really would like to have a UI for analytics. I created this ticket a while back: https://github.com/Ethan3600/magento2-CronjobManager/issues/20 but I haven't had the time to invest in a huge feature like this.

Going to close this for now, feel free to comment!
