### ISSUE TITLE
Long Tasks Show Error Status & Later Complete Successfully

### ISSUE THREAD

**Issue by uandiweb** [Ethan3600/EthanYehuda_CronjobManager#120]
I've some tasks that take 30-40 minutes to complete. After ~3 minutes those tasks are marked as error. Later, after the task finishes successfully, it's marked correctly has "Success".

**Comment by MellenIO** [comment]
@uandiweb are there any messages on the "error" cronjobs?
If you run:
```sql
select job_code, messages, count(messages) as unique_count from cron_schedule where job_code in('my', 'erroring', 'cronjob', 'codes') and status = 'error' and messages is not NULL group by messages
``` 
That query should get you all of the unique errors put in the database.

**Comment by fredden** [comment]
This sounds like the same issue as #98. Can you confirm if you are running Magento cron distributed across multiple hosts/servers?

**Comment by fredden** [comment]
@uandiweb I'm closing under the assumption that this is a duplicate of #98. If that's not the case, please let us know.
