### ISSUE TITLE
Invalid Cron Expression reported incorrectly

### ISSUE THREAD

**Issue by aligent-lturner** [Ethan3600/EthanYehuda_CronjobManager#122]
**Describe the bug**
The schedule editor does not allow cron expressions containing commas, despite them being valid.

**To Reproduce**
1. Edit the configuration of an existing cron job.
2. Modify the schedule to `5,15 * * * *` (run at 5 past and 15 past every hour)
3. Attempt to save the schedule.

**Expected behavior**
The schedule is updated successfully.

**Environment (please complete the following information):**
 - OS: CentOS
 - Browser: Chrome
 - Cron Job Manager Version: 1.6.3
 - Magento Version: 2.2.7
 - PHP Version: 7.0.33

**Additional context**
The regular expression being used by `ethanyehuda/magento2-cronjobmanager/view/adminhtml/web/js/cron-validator.js` should be updated to allow comma-separated lists.

**Comment by Ethan3600** [comment]
Hi @aligent-lturner, Sorry for the late response. I have to admit, I'm not proud of that validator... It needs to be revisited. Thanks for filing this bug!

**Comment by choussamaster** [comment]
Hi any news about this validator ?

**Comment by fredden** [comment]
A fix for this has been [released in version 2.1.0](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v2.1.0).
