### ISSUE TITLE
Add php 7.3 support for Magento 2.3.3

### ISSUE THREAD

**Issue by sedax90** [Ethan3600/EthanYehuda_CronjobManager#130]
The new Magento 2.3.3 release officially support php 7.3, but module requirement is locked to 7.2, is it possible to change it?

**Comment by MellenIO** [comment]
I've created a PR for this #131 since there are no compatibility issues. Let's just hope it gets merged in :)

**Comment by Ethan3600** [comment]
Currently in 1.x-develop.

Will be available in the next release

**Comment by Ethan3600** [comment]
Sorry for the delay. This is available in the latest release. Going to close, but feel free to comment!
