### ISSUE TITLE
Is the module in the marketplace a rip-off or yours?

### ISSUE THREAD

**Issue by tylers-username** [Ethan3600/EthanYehuda_CronjobManager#132]
I installed [this](https://marketplace.magento.com/kiwicommerce-module-cron-scheduler.html) before being made aware of this repository here.

It has fewer releases and branding appears to be different. Curious if this is your module?

**Comment by Ethan3600** [comment]
I'm getting a 404 on that link to gitlab. Maybe I don't have permission to view it?

But, I can tell you that I've never published anything to gitlab.

**Comment by tylers-username** [comment]
🤦‍♂️ sorry, meant to link here: https://marketplace.magento.com/kiwicommerce-module-cron-scheduler.html

Original comment updated as well.

**Comment by Ethan3600** [comment]
That's not my module. But, I don't think they're trying to rip anyone off.

Thanks for keeping an eye out! 

Going to close this.
