### ISSUE TITLE
Scheduler still tries to run jobs for disabled modules

### ISSUE THREAD

**Issue by hewgim** [Ethan3600/EthanYehuda_CronjobManager#135]
**Describe the bug**
There are certain situations where the scheduler tries to run jobs for disabled modules. For example I disabled the Yotpo module but in the cron schedule table I can see the error message: No callbacks found for cron job yotpo_yotpo_orders_sync. It only seems to happen if you had previously changed the job frequency of a module that you then disable.

**To Reproduce**
1. Change the job frequency of say the yotpo_yotpo_orders_sync job to */5 * * * *
2. Disable the Yotpo module, (clean cache etc)
3. You will still see the yotpo job in the job configuration grid (although the job code is blank)
4. The scheduler will still try and run the job and you will see the error: No callbacks found for cron job yotpo_yotpo_orders_sync in the dashboard view

**Expected behavior**
If a module is disabled, no related jobs for that module should appear in the job configuration grid and no jobs for that module should be run

**Screenshots**

**Environment (please complete the following information):**

 - Cron Job Manager Version 1.8.0
 - Magento Version 2.3.3
 - PHP Version 7.2.25

**Additional context**
A workaround: Deleting the relevant entry in the core_config table seems to fix the problem

e.g. Deleting crontab/default/jobs/yotpo_yotpo_orders_sync/schedule/cron_expr for the yotpo_yotpo_orders_sync job prevents the yotpo_yotpo_orders_sync appearing in the job configuration grid and also prevents it running

**Comment by Ethan3600** [comment]
This sounds like a bug in either the Yopto module or Magento (my gut says the former).

To test, see if this happens without the CJM manager installed. Going to close this for now. Please feel free to comment if you find anything.
