### ISSUE TITLE
Can't find menu in backend

### ISSUE THREAD

**Issue by Eddcapone** [Ethan3600/EthanYehuda_CronjobManager#136]
There is no info on where I can find the menu in the backend. I searched under "System" but found nothing.

**Comment by Ethan3600** [comment]
Hi @Eddcapone thanks for using the CJM!

In order to help, can you provide your Magento, PHP, and CJM versions?

**Comment by Eddcapone** [comment]
Nevermind. I executed `php bin/magento module:status` and got:

```
List of disabled modules:
Aheadworks_Wbtab
Apptrian_ImageOptimizer
EthanYehuda_CronjobManager
Yireo_Webp2
```

So I just had to enable the module. I was not aware about this, because some modules just work without having to enable them manually.

You should add installation instructions and a screenshot or text showing that we can find the configuration under "System-> Tools -> Cron Job Manager"

**Comment by Ethan3600** [comment]
Weird. I've never had to enable it manually. Usually works after setup:upgrade. Agreed, we can always use more docs! 

I'm going to go ahead and close this, but thanks for logging this! Please let me know if you experience any issues using the CJM!
