### ISSUE TITLE
Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by bzneil** [Ethan3600/EthanYehuda_CronjobManager#140]
Hi,
I've just installed on Magento 2.3.4, if I navigate to System>Tools>Cron Jib Manager it takes me backto admin dashboard with the message
Invalid security or form key. Please refresh the page.

Any ideas? I've refreshed the cache, issue still persists. Thanks

**Comment by Ethan3600** [comment]
I'd check if this is happening elsewhere. This doesn't seem like a CJM issue at face value.

**Comment by bzneil** [comment]
Thanks, generated classes again, cleared cache and loads ok now
