### ISSUE TITLE
Magento 2.4 support

### ISSUE THREAD

**Issue by kirkmadera** [Ethan3600/EthanYehuda_CronjobManager#152]
We are working in 2.4 for current and future projects and had to fork this repo to get this module in. Would love to see 2.4 support.

**Describe the solution you'd like**
We have installed this locally on a 2.4 instance and don't see any issues. To add support, it's likely as simple as adding `~104.0.0` to the `magento/framework` requirement.

**Describe alternatives you've considered**
Another option would be to open up the `magento/framework` requirement to `*`.

**Comment by SAN1TAR1UM** [comment]
I second this request, I love this module but I need it to work with 2.4

**Comment by gaiterjones** [comment]
I third this request. Please update the repo for framework 104 compatibility in composer.

**Comment by boehsermoe** [comment]
The PR still open... 😞  some other solutions to install it?

**Comment by kirkmadera** [comment]
In the immediate, you can clone from https://github.com/rmgmedia/magento2-CronjobManager. It's a very short-term solution as I don't plan to maintain this for updates. You can also fork it yourself and apply this change.

**Comment by Ethan3600** [comment]
Sorry for the late response. Been out of commission for a bit :disappointed: I'll get a release out ASAP.

**Comment by seansan** [comment]
Is there a release date for M2.4 support?

Can we also imply php 7.4 support then?

SUPER WORK thx

**Comment by Ethan3600** [comment]
Hello friends!

We should be good to go in the latest release (v1.11.2).

I'll close this issue for now, but if anyone experiences any issues regarding 2.4 support, please feel free to log another bug or comment here!
