### ISSUE TITLE
Dashboard entries don't show any information

### ISSUE THREAD

**Issue by norgeindian** [Ethan3600/EthanYehuda_CronjobManager#156]
**Describe the bug**
When opening the cronjob dashboard there are entries like expected. But instead of showing actual information, the columns are more or less empty. 

**To Reproduce**
1. Go to System -> Tools -> Cron Job Manager

**Expected behavior**
I would expect to see the cronjob dashboard with filled entries.

**Screenshots**
![image](https://user-images.githubusercontent.com/11156287/95565600-bb261b00-0a20-11eb-92ac-94edf506d782.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Cron Job Manager Version 1.11.1
 - Magento Version 2.4.0
 - PHP Version 7.4

**Additional context**
When opening the dev tools, I see the following error:
![image](https://user-images.githubusercontent.com/11156287/95565775-f1639a80-0a20-11eb-8bcc-0872a215140c.png)

**Comment by Ethan3600** [comment]
Hello @norgeindian I just made a new release (v1.11.2), which should have the fix and tested it. Give this another whirl after an upgrade.

I'll close this for now, but if there are any issues, please feel free to comment and I'll open this issue again!
