### ISSUE TITLE
Compatible with PHP 8.1

### ISSUE THREAD

**Issue by AdamC3Media** [Ethan3600/EthanYehuda_CronjobManager#171]
Hi,

Will your module be compatible with PHP 8.1 in the near future? I'm trying to update my client to 2.4.4 on PHP 8.1, but the latest version available is 7.4

Kind regards.

Adam

**Comment by mamsincl** [comment]
Oy, @Ethan3600 

any info on this, please?

Thanks,
R.

**Comment by Ethan3600** [comment]
We have a PR open: https://github.com/Ethan3600/magento2-CronjobManager/pull/172

Added a comment, but I think we'll make a release soon
