### ISSUE TITLE
Email notifications When Cron Job fails

### ISSUE THREAD

**Issue by Ethan3600** [Ethan3600/EthanYehuda_CronjobManager#18]
Add a configuration to enter 1 or more email addresses to alert when a cron job fails

**Comment by sprankhub** [comment]
Thanks for this extension! However, I will use another extension for now, because this feature is missing. IMHO, it is a must-have.

**Comment by schmengler** [comment]
I'm working on this now

**Comment by sprankhub** [comment]
Thanks a lot @schmengler!
