### ISSUE TITLE
PHP 8.1 | Deprecated Functionality: Function strftime() is deprecated...

### ISSUE THREAD

**Issue by ssstankiewicz** [Ethan3600/EthanYehuda_CronjobManager#183]
After updating magento to 2.4.4 and PHP to 8.1, the module is unusable. When trying to run from the admin panel of the action 'Dispatch' or using the command 'cronmanager: runjob', errors related to 'Deprecated functionality' appear.

This function is used several times in the module.

**Environment**
 - Cron Job Manager Version 1.3.1
 - Magento Version 2.4.4
 - PHP Version 8.1

**Comment by fredden** [comment]
When I run `phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 8.1` on this repository, no errors are reported.

I've tested this just now and can see that `strftime()` has been deprecated. I'll look to remove its usage in the module.

**Comment by fredden** [comment]
> When I run `phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 8.1` on this repository, no errors are reported.
> 
> I've tested this just now and can see that `strftime()` has been deprecated. I'll look to remove its usage in the module.

It looks like the compatibility checker tool has been updated here to include this deprecation, but no new version has been released yet. https://github.com/PHPCompatibility/PHPCompatibility/pull/1321

**Comment by fredden** [comment]
Thanks for your report @ssstankiewicz. I've fixed this in #184.

**Comment by ssstankiewicz** [comment]
Thanks @fredden Do you plan to merge it into main branch?

**Comment by fredden** [comment]
I don't have permission on GitHub to do that. We'll need to wait for @Ethan3600.

Meanwhile, one can apply the patch with `cweagans/composer-patches` or similar.

**Comment by ssstankiewicz** [comment]
Okay, thanks.

**Comment by mamsincl** [comment]
+1 please

**Comment by Ethan3600** [comment]
Just pushed out a new [release](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v1.13.2) . I know I've been late to the party... I think I need help maintaining this project. I don't know what the avenue is to ask for help 😞

**Comment by mamsincl** [comment]
like you did :D 

I am happy spending some time helping you out

**Comment by fredden** [comment]
I can help out too if you'd like.
