### ISSUE TITLE
Magento 2.4.5 - Status Column (html.js) not working

### ISSUE THREAD

**Issue by mvenghaus** [Ethan3600/EthanYehuda_CronjobManager#186]
**Describe the bug**
The status column in the listing grid doesn't work with magento 2.4.5.

[ERROR] Failed to load the "ui/grid/cells/html" template requested by "cronjobmanager_manage_grid.cronjobmanager_manage_grid.cronjobmanager_manage_columns.status".

**To Reproduce**
1. open grid in admin

**Expected behavior**
status column should show rendered status html

**Environment (please complete the following information):**
- magento 2.4.5

**Additional context**
Maybe I'm wrong but I don't see the need for the custom html.js
EthanYehuda_CronjobManager/js/grid/columns/html

I changed
`<item name="component" xsi:type="string">EthanYehuda_CronjobManager/js/grid/columns/html</item>`
to
`<item name="bodyTmpl" xsi:type="string">ui/grid/cells/html</item>`

and everything seems to work. But I'm not sure I'm considered all use cases.

**Comment by fredden** [comment]
This is fixed in https://github.com/Ethan3600/magento2-CronjobManager/pull/179.

**Comment by sandeep570** [comment]
@fredden  I have fix for this and I clearly don't see the fix so here is the code below 
`
        /**
         * UnsanitizedHtml version of getLabel.
         *
         * @param {Object} record - Data to be preprocessed.
         * @returns {String}
         */
        getLabelUnsanitizedHtml: function (record) {
            return this.getLabel(record);
        },`

Add above codes in the file EthanYehuda/CronjobManager/view/adminhtml/web/js/grid/columns/html.js after the getLabel function so issue gets fixed.
@mvenghaus

**Comment by fredden** [comment]
@sandeep570 a complete fix for this is in #179.
@Ethan3600 please can you merge #179 and/or grant me permission to do so.

**Comment by fredden** [comment]
Thanks @Ethan3600. I've merged #179 and created [a release (v1.13.3)](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v1.13.3) to solve this issue.
