### ISSUE TITLE
PHP 8.2 / Magento 2.4.6 support

### ISSUE THREAD

**Issue by rutgerrademaker** [Ethan3600/EthanYehuda_CronjobManager#188]
**Is your feature request related to a problem? Please describe.**

Although php 8.2 is not a requirement for magento 2.4.6 it would be good to be able to see if the module has any issues when installed in a php 8.2 environment running magento 2.4.6.

Forpersonal  testing-purposes in Magento 2.4.6-beta8 i've already created a fork

https://github.com/Ethan3600/magento2-CronjobManager/compare/1.x...rutgerrademaker:magento2-CronjobManager:1.x

This does not address php 8.2 support, it only adds the option to install it under PHP 8.2
As I'm using a magento beta version I also had to be less strict on the magento framework requirements (and add the magento one)

**Describe the solution you'd like**

PHP 8.2 support to be added
Magento 2.4.6 support to be added

**Describe alternatives you've considered**
None, this extension is doing an excellent job :)

**Additional context**

My fork (at least locally) seems to work as expected
I have not yet ran any serious tetsts

**Comment by fredden** [comment]
Thanks @rutgerrademaker. I've opened #189 to adjust the requirements in `composer.json`. When I get access to Magento 2.4.6 (which should be tomorrow evening), I'll review this again.

**Comment by fredden** [comment]
I've released version 1.15.0 which includes the changes in #190 and #189.
https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v1.15.0
