### ISSUE TITLE
Sort by group results in Zend_Db_Statement_Exception

### ISSUE THREAD

**Issue by jhillpolywood** [Ethan3600/EthanYehuda_CronjobManager#196]
**Describe the bug**
`group` is both a reserved keyword in MariaDB (and probably MySQL 8) and a column name in the extended `cron_schedule` table, causing an exception when the ORM stitches together a query that sorts by `group` in the Cron Job Manager grid.

**To Reproduce**
1. Go to Cron Manager Dashboard grid from Magento admin (System > Tools > Cron Job Manager)
2. Initiate sort by 'Group' column
4. The following error is logged in `var/exception.log`:

```Next Zend_Db_Statement_Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group ASC LIMIT 20' at line 1, query was: SELECT `main_table`.* FROM `cron_schedule` AS `main_table` ORDER BY group ASC LIMIT 20 in /vendor/magento/framework/DB/Statement/Pdo/Mysql.php```

**Expected behavior**
Grid is able to sort by group field.  Explicitly surrounding the `group` column identifier with tick quotes in the a direct SQL query appears to address this issue.

**Environment**
 - DB: MariaDB 10.4
 - Cron Job Manager Version - 1.15.1
 - Magento Version - 2.4.5-p1
 - PHP Version - 8.1.x

**Comment by fredden** [comment]
Thank you for your report. I have opened https://github.com/magento/magento2/pull/37387 to fix this bug in Magento.

**Comment by jhillpolywood** [comment]
Thanks for doing that @fredden; I'll follow along.

**Comment by peterjaap** [comment]
@jhillpolywood the Magento bug has been merged into 2.4-develop and will be released as a part of 2.4.7. You could test out the latest beta to see if it fixes your problem.

**Comment by fredden** [comment]
https://github.com/magento/magento2/pull/37387 has been released today with Magento v2.4.7.
