### ISSUE TITLE
2.1.0 Not Compatible With Magento < 2.4.6

### ISSUE THREAD

**Issue by sprankhub** [Ethan3600/EthanYehuda_CronjobManager#197]
**Describe the bug**
Due to the dependency on `symfony/console` version 5, this module cannot be installed in Magento below 2.4.6.

https://github.com/Ethan3600/magento2-CronjobManager/blob/0143f39abef73c7a19e9ad65e73a8238c40273a5/composer.json#L13

Even Magento 2.4.5-p3 requires `symfony/console` in version 4 only:

https://github.com/magento/magento2/blob/2.4.5-p3/composer.json#L76

**To Reproduce**
1. Require module in any Magento version below 2.4.6.
2. See that only version 1.14.0 and not 2.1.0 is installed.

**Expected behavior**
The module is installed.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Ubuntu 22
 - Browser Chrome
 - Cron Job Manager Version 1.14.0
 - Magento Version 2.4.5-p3
 - PHP Version 8.2

**Additional context**
n/a

**Comment by lewisje** [comment]
On a related note, when I tried running `composer require` on a Magento 2.4.0 installation on PHP 7.3, I still got the suggested version constraint of `^2.1`, even though symfony/console is version-locked there too; I ended up picking `^1.14` and then it installed. (1.15 also has a hard-coded dependency on symfony/console 5 or higher and requires the same sort of patch.)

**Comment by fredden** [comment]
> On a related note, when I tried running `composer require` on a Magento 2.4.0 installation on PHP 7.3, I still got the suggested version constraint of `^2.1`, even though `symfony/console` is version-locked there too; I ended up picking `^1.14` and then it installed. (1.15 also has a hard-coded dependency on `symfony/console` 5 or higher and requires the same sort of patch.)

@lewisje what version of Composer are you using? [Version 2.5.0](https://github.com/composer/composer/releases/tag/2.5.0) comes with an improvement to the version-finding algorithm.

**Comment by fredden** [comment]
A quick look suggests this constraint was introduced to `composer.json` in https://github.com/Ethan3600/magento2-CronjobManager/pull/189, which landed in v1.15.0. This means that all versions before this shouldn't suffer from this constraint (although they do have an undeclared dependency on `symfony/console`).

The [supported versions matrix](https://github.com/Ethan3600/magento2-CronjobManager/tree/2.x#support) does list version 1.15.0 for Magento 2.4.6 as the lowest supported version, but all prior versions of Magento have a lower minimum version number.

**Comment by fredden** [comment]
I think I've worked out what's gone wrong here. For some reason the `1.x` branch was been tagged as version `2.1.0` by mistake. I've now tagged the `1.x` branch as `1.16.0` and the head of the `2.x` branch as `2.1.1`. Version `2.1.0` shouldn't be compatible with Magento versions below 2.4.4 (ref https://github.com/Ethan3600/magento2-CronjobManager/tree/2.x#support).

I'd like to delete version `2.1.0`, but I don't think semver allows this.

**Comment by sprankhub** [comment]
That does not fix the issue for me, @fredden. I use 2.4.5-p3, which should be compatible with version 2 according to the README. However, Magento 2.4.5-p3 seems to require `symfony/console` version 4.

    $ composer why-not ethanyehuda/magento2-cronjobmanager 2
    magento/project-community-edition   2.4.5-p3 requires         ethanyehuda/magento2-cronjobmanager (^1.14) 
    ethanyehuda/magento2-cronjobmanager 2.0.0    requires         symfony/console (^5.0)                      
    magento/project-community-edition   2.4.5-p3 does not require symfony/console (but v4.4.49 is installed)  
    Not finding what you were looking for? Try calling `composer update "ethanyehuda/magento2-cronjobmanager:2" --dry-run` to get another view on the problem.

And

    $ composer why-not symfony/console 5
    friendsofphp/php-cs-fixer                     v3.4.0     requires  symfony/console (^4.4.20 || ^5.1.3 || ^6.0) 
    magento/composer                              1.8.0      requires  symfony/console (~4.4.0)                    
    magento/framework                             103.0.5-p3 requires  symfony/console (~4.4.0)                    
    magento/magento2-base                         2.4.5-p3   requires  symfony/console (~4.4.0)                    
    magento/magento2-functional-testing-framework 3.10.2     requires  symfony/console (^4.4||^5.4)                
    magento/product-community-edition             2.4.5-p3   requires  symfony/console (~4.4.0)                    
    symfony/http-kernel                           v4.4.50    conflicts symfony/console (>=5)                       
    symfony/console                               v5.0.0     requires  php (^7.2.5 but 8.1.17 is installed)        
    Not finding what you were looking for? Try calling `composer update "symfony/console:5" --dry-run` to get another view on the problem.

**Comment by fredden** [comment]
Thanks for following up @sprankhub. I've reviewed and tested and merged #198, and released this as version 1.16.1 (and merged into the 2.x branch and tagged as 2.1.2). Please can you test and report back?

**Comment by sprankhub** [comment]
Confirming that this fixed the issue. Re-requiring the module now installed `v2.1.2`. Thanks, @fredden!

**Comment by lewisje** [comment]
> > On a related note, when I tried running `composer require` on a Magento 2.4.0 installation on PHP 7.3, I still got the suggested version constraint of `^2.1`, even though `symfony/console` is version-locked there too; I ended up picking `^1.14` and then it installed. (1.15 also has a hard-coded dependency on `symfony/console` 5 or higher and requires the same sort of patch.)
> 
> @lewisje what version of Composer are you using? [Version 2.5.0](https://github.com/composer/composer/releases/tag/2.5.0) comes with an improvement to the version-finding algorithm.

I use `1.10.22` and do not have the level of access needed to upgrade Composer, or else I would have upgraded it years ago.
