### ISSUE TITLE
Can't execute action Schedule Now Cron Job in Grid Mass Action

### ISSUE THREAD

**Issue by LukaszZabielskiMonogo** [Ethan3600/EthanYehuda_CronjobManager#199]
**Describe the bug**
Can't execute action Schedule Now Cron Job in Grid Mass Action.

**To Reproduce**
1. Go to Job List
2. Select Job on Grid
3. Select Mass Action Schedule Now

**Expected behavior**
Action Schedule Now executes the cronjob.

**Environment (please complete the following information):**
 - OS: All
 - Browser All
 - Cron Job Manager Version 2.1.2
 - Magento Version [e.g. 2.4.6-p1]
 - PHP Version [e.g. 8.2]

**Additional context**
Error: Call to undefined method EthanYehuda\CronjobManager\Model\Manager::scheduleNow() in /code/vendor/ethanyehuda/magento2-cronjobmanager/Controller/Adminhtml/Config/Job/MassScheduleNow.php:42
Stack trace:
#0 /code/vendor/magento/framework/Interception/Interceptor.php(58): EthanYehuda\CronjobManager\Controller\Adminhtml\Config\Job\MassScheduleNow->execute()

**Comment by fredden** [comment]
Thanks for the report. I've fixed this in 45728221a34c69554ce1ad4515e1b04ac0cdf8e5, which I've released as [version 2.1.3](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v2.1.3).

**Comment by LukaszZabielskiMonogo** [comment]
Good job, thanks for quick fix.
