### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by norgeindian** [Ethan3600/EthanYehuda_CronjobManager#205]
**Is your feature request related to a problem? Please describe.**
As Magento 2.4.7, which will be published in 3 weeks will support PHP 8.3, it would be awesome, if this module would support PHP 8.3 as well.

**Describe the solution you'd like**
Add Support for PHP 8.3

**Comment by peterjaap** [comment]
We need this too, only this module is blocking us to upgrade to 8.3.

**Comment by fredden** [comment]
@peterjaap I expect to be able to merge #206 on 9th April when Magento v2.4.7 gets released.

**Comment by fredden** [comment]
https://github.com/Ethan3600/magento2-CronjobManager/pull/206 has been merged and released as [v2.2.1](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v2.2.1)
