### ISSUE TITLE
Create Timeline Feature

### ISSUE THREAD

**Issue by Ethan3600** [Ethan3600/EthanYehuda_CronjobManager#29]
## Objective: 

Rebrand existing "timeline" as visualizer and create a new Timeline based on something like [Google charts api](https://developers.google.com/chart/interactive/docs/gallery/timeline)

The goal is to have a higher level perspective, over the visualizer, to gather a more granular view of cron jobs and where they are running.

**Comment by hanhpv** [comment]
This is exactly what's I'm looking for. Billion thanks for your great extension 👍

**Comment by Ethan3600** [comment]
@hanhpv it's coming!

**Comment by Ethan3600** [comment]
Possible options:

* https://github.com/commodityvectors/d3-timeline

* http://visjs.org/

* https://developers.google.com/chart/interactive/docs/gallery/timeline

**Comment by Ethan3600** [comment]
## Rough Draft Of (Potential) Custom Implementation

Rather than using a 3rd party library, I'm flirting with the idea of creating a UiComponent from scratch and building out a fully featured timeline component, taking advantage of all the knockout data binding features available. Below are some (very) rough draft work planning, and architectural outlining for the timeline component

I'd like to have the timeline update in **real time** (i.e. every 3 seconds the view will update). This will give us a cool interface that will allow us to watch magento schedule jobs without refreshing the page.

### Architecture

![20180401_174716](https://user-images.githubusercontent.com/6549623/38178040-2b0b6558-35d8-11e8-8d95-34848f854ff6.jpg)

### Timeline Draft

![20180401_174758](https://user-images.githubusercontent.com/6549623/38178045-492df244-35d8-11e8-9c3c-5ced7a073f1c.jpg)

### UiComponent Outlining

![20180401_174702](https://user-images.githubusercontent.com/6549623/38178053-7869f77e-35d8-11e8-8afb-3d1a1b6da5ec.jpg)

### Workplan 

![20180401_174648](https://user-images.githubusercontent.com/6549623/38178062-95d15e06-35d8-11e8-9985-a534f3b16959.jpg)

### Additional/Redundant... Stuff

![20180401_174728](https://user-images.githubusercontent.com/6549623/38178065-ab6b12c0-35d8-11e8-9d2b-d0e6a1dd3bcb.jpg)

**Comment by Ethan3600** [comment]
Decided to go with the custom implementation.

Here's a sneak peak at the first working iteration:

![image](https://user-images.githubusercontent.com/6549623/38970603-71e12cd0-4364-11e8-9883-73c522b9e8e3.png)

Really excited to get this feature done!

**Comment by hanhpv** [comment]
Really great work so far. Can’t wait to have this working. Big thank for your contribution.

**Comment by Ethan3600** [comment]
@hanhpv upgrade to v1.4.0 :wink: 

Let me know what you think.

Going to close this issue; please open an issue if you spot anything.

Thank you for using the CJM!
