### ISSUE TITLE
"Schedule now" 

### ISSUE THREAD

**Issue by edkoster** [Ethan3600/EthanYehuda_CronjobManager#51]
Using version 0.4.0 on Magento 2.1.10 in production mode i get this error:

`[Tue May 01 15:11:14.275469 2018] [proxy_fcgi:error] [pid 3946] [client 87.213.39.106:16732] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to EthanYehuda\\CronjobManager\\Controller\\Adminhtml\\Config\\Job\\MassScheduleNow::__construct() must be an instance of Magento\\Framework\\View\\Result\\PageFactory, instance of Magento\\Framework\\ObjectManager\\ObjectManager given, called in /var/www/vhosts/score/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/vhosts/score/httpdocs/vendor/ethanyehuda/magento2-cronjobmanager/Controller/Adminhtml/Config/job/MassScheduleNow.php:19\nStack trace:\n
#0 /var/www/vhosts/score/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): EthanYehuda\\CronjobManager\\Controller\\Adminhtml\\Config\\Job\\MassScheduleNow->__construct(Object(Magento\\Framework\\ObjectManager\\ObjectManager))\n
#1 /var/www/vhosts/score/httpdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('EthanYehuda\\\\Cro...', Array)\n
#2 ...\n', referer: https://support-score.itnova.nl/sitemanager_53RfIfauG6CnZGS/cronjobmanager/config/index/key/dd48cb763ad077fb2bf32652df3d040976b30970adfea962d9290b31a0943746/`

when i use the "Schedule now" option on from the Job configuration.

i've done some debugging and found out that renaming 
`magento2-cronjobmanager/Controller/Adminhtml/Config/job`
to 
`magento2-cronjobmanager/Controller/Adminhtml/Config/Job`

solves the issue.

**Comment by Ethan3600** [comment]
Good catch!  Would you mind opening a PR? I'll make a patch release after it gets merged in.

Thank you for using the CJM!

**Comment by edkoster** [comment]
Thanks for your quick response. 
I'll try to make some time for a pullrequest tomorrow.

**Comment by Ethan3600** [comment]
Awesome! Looking forward to it.

**Comment by edkoster** [comment]
i've created https://github.com/Ethan3600/magento2-CronjobManager/pull/52

**Comment by Ethan3600** [comment]
I made a release for v1.5.1 and v0.4.1 to mitigate this issue. I'll go ahead and close this out, but feel free to comment if the error persists.

Thank you for your contribution @edkoster!
