### ISSUE TITLE
Timeline Performance Slows Down After ~2k records

### ISSUE THREAD

**Issue by Ethan3600** [Ethan3600/EthanYehuda_CronjobManager#53]
The timeline seems to slow down after hitting around 2k records in cron_schedule.

Wild guess: This is likely due to all the subscribers KO has for each binding

The goal of this Issue is to resolve problems with speed, and the amount of records we can handle in the timeline.

There should be a "max" number of records we support because there's an argument that you shouldn't have over a certain amount of records stored in cron_schedule.  We'll definitely want to get a specific number for this 

---

This is a follow up issue that was derived from issue #50

**Comment by Jeroenll** [comment]
Might be an idea: Load jobs of last 12/24h and use those in the timeline instead of all jobs?

**Comment by Ethan3600** [comment]
@JeroenVanLeusden good idea. I wouldn't be opposed to making that a setting, but I think the JS needs a little work too. 

Ideally, we should be able to update the layout relatively quickly regardless of the amount of records we stuff into it. I want to dig deeper and figure out what is causing the "jankyness"

**Comment by Ethan3600** [comment]
Did a little digging last night and found out something interesting:

I think one of the culprits to the jankyness is attributed to tooltip.js 

In the below call tree, you can see we're spending 34% of the time within toolip.js's init() method defined here: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/web/js/lib/knockout/bindings/tooltip.js#L723

![image](https://user-images.githubusercontent.com/6549623/39663972-0c0e7028-504a-11e8-8071-fd5ed40874ea.png)

I recorded another session **without** tooltips by commenting out [this line of code](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/view/adminhtml/web/templates/timeline/timeline.html#L65), which renders the tooltip for each cron.

![image](https://user-images.githubusercontent.com/6549623/39664040-227965ec-504b-11e8-9cb2-ec22b8a3000b.png)

You can see that we're spending most of our time within the firefox "graphic" function, which I have no idea what that is but I imagine it's a low level "painting" mechanism or something. When I removed the tooltip.js functionality I noticed a substantial increase in performance.

A solution here would be to use a CSS tooltip rather than the JS tooltip. I _think_ magento has a mixin that we can use for this, so that may solve that problem.

----

It's still a bit slow, even after removing the tooltip KO binding, so I'll need to do some more digging.

**Comment by Ethan3600** [comment]
So... to my dismay, the CSS tooltip didn't help much.  It somehow made it worse! I'm starting to think that KnockoutJs just can't handle iterating over large data sets, which would require us to really limit the amount of crons we can load in the timeline. Not ideal.

But... there is some sliver of hope:
http://output.jsbin.com/dakihezega/2

There's a plugin called "fastForEach" (which is luckily packaged with Magento's code base :fireworks: ) If I could leverage this somehow with my custom foreachProp binding, maybe we won't have to filter the amount of crons!

**Comment by Ethan3600** [comment]
Sorry for blowing up the thread (having too much fun here), but I was totally wrong.

The issue wasn't the tooltip... it was the `render` attribute, which is a wrapper for KO's `template` binding. Also, KO's `template` was overridden by Magento to ["support asynchronous loading of templates"](https://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/knockout-bindings.html#template)

This slowed things down tremendously. See before and after flame charts:

### Before

![image](https://user-images.githubusercontent.com/6549623/39677291-83b4ea88-5146-11e8-8070-d0b33a66cdbf.png)

### After

![image](https://user-images.githubusercontent.com/6549623/39677298-93695482-5146-11e8-85ad-ff522c1805f6.png)

Not sure if fastForEach helped much, but I'll keep it for now.

I'm going to begin stress testing to see how many records we can handle now.

**Comment by Ethan3600** [comment]
So, we can comfortably load over 4k records with little to no jankyness. We can even push it to 6k with a little lag.

Moreover, I was able to load **16768 records** without crashing my browser (albeit, really slowly). To test anything more than that isn't worth it because it's arguable that 16k is considered "unhealthy"

I'd say, this is a tiny victory, but there just doesn't seem like a way we can (comfortably) support any more than 6k records.

I wonder if we should put a warning if there's more than a certain amount of records in the database.

Question is: _at what point is the amount of records in `cron_schedule` universally deemed "unhealthy?"_ I have my own opinions, but I don't want to "impose" that on users. 

Very confused on what to do should do here...

**Comment by Ethan3600** [comment]
@JeroenVanLeusden I created a new release (v1.6.1) that will speed up the timeline tremendously, and give it the ability to handle more records.

While I did not include the filter you suggested earlier, I felt like this latest performance boost in combination with [this new feature](https://github.com/Ethan3600/magento2-CronjobManager/pull/57), we _should not_ face the issues you described in issue #50 

I'm trying to avoid the filter as much as possible because I'd rather have as much information presented to the user as possible; but if it's still an issue, please open another issue or I'll reopen this one.

Closing this for now.
