### ISSUE TITLE
Cron stop working after installation

### ISSUE THREAD

**Issue by Superheld** [Ethan3600/EthanYehuda_CronjobManager#67]
First, I could not longer login to my backend. Error was: `Class Magento\\Framework\\Stdlib\\Cookie\\PublicCookieMetadataFactory does not exist`

I fixed that with flushing var/generation and a `magento setup:di:compile`

After that i could login to the backend but now all tasks, scheduled for execution after installation-time are still open (seen in the database). If i want to see the  list in my backoffice, it loads infinity. Also the timetable is not loading and flush jobs did nothing (no changes if i check db).

i did this by flush it with phpmyadmin now. this has no effect to the problems, even without any rows in my db the tables in backoffice still loading infinity.

now i removed the tool with composer. by remving it it installas tons of new tools (zendframework, phpunit, and some other stuff). my magento still works but this toll is still blocking my cron jobs now!

**UPDATE**: After flusching all jobs in db a new punch of jobs where created automatically (not as configured every 30min, now its every 5 min.)  it works again. but the timetable and -frame still loading infinty

**Comment by Ethan3600** [comment]
Hi @Superheld thanks for using the CJM!

The first red flag here is when you say "var/generation," which makes me think you're using Magento 2.1.x. The CJM used to support Magento 2.1.x in the earlier versions (0.x releases), but **no longer does**.

The other red flag is when you say "but the timetable and -frame still loading infinty," which makes me think you're using v1.x of the CJM.  _Only v0.x of the CJM is compatible with Magento 2.1.x_

I, personally, will not continue to support v0.x of the CJM anymore, but you can still install it from composer and I'll still be accepting pull requests.

The 0.x branch is very outdated and [requires a ton of backports](https://github.com/Ethan3600/magento2-CronjobManager/compare/0.x...1.x?expand=1)

I suggest uninstalling the CJM unless you're going to be working with Magento 2.2.x.

**Comment by Superheld** [comment]
We are using 2.2.4, i had to tell you this, right.

I checked now the situation. Seems only the listing-problem left, all other stuff looks normal at this time.

**Comment by Ethan3600** [comment]
I should probably have a template or something for issues. No worries.

What version of the CJM are you using?

Can you elaborate on the "listing-problem"?

Please provide some steps to reproduce and maybe some screenshots (please :) ).

**Comment by Ethan3600** [comment]
Since I haven't heard a response in three days, I assume this issue is resolved. Please feel free to comment if you're still experiencing issues.
