### ISSUE TITLE
Issue with timeline when there are no jobs

### ISSUE THREAD

**Issue by kerlama** [Ethan3600/EthanYehuda_CronjobManager#68]
Hi,

its likely to happen, but when there are no jobs timeline is messed up:

http://prntscr.com/kg4s67

Ivan

**Comment by Ethan3600** [comment]
Thanks for using the CJM and reporting this bug!

I'm able to reproduce this and I'll  have a fix for it in the next release.

Probably just needs a message saying "There's no cron jobs in Magento"

**Comment by Ethan3600** [comment]
fixed in v1.6.3
