### ISSUE TITLE
_module.css 404 in Production mode

### ISSUE THREAD

**Issue by kirkmadera** [Ethan3600/EthanYehuda_CronjobManager#70]
When running in Production mode. a 404 response is shown in the network console that _module.css could not be included. This is because the less is not compiled on the fly into the css file. Instead, production mode imports all _module.less files from modules into the main styles.css file. In developer mode, this file is also included by default. The css include in layout is unnecessary in developer mode and creates a 404 in Production mode.

**Comment by Ethan3600** [comment]
Fixed in v1.6.3
