### ISSUE TITLE
Magento 2.3 compatibility?

### ISSUE THREAD

**Issue by peterjaap** [Ethan3600/EthanYehuda_CronjobManager#79]

**Comment by Ethan3600** [comment]
I think someone tested it out and made a PR: https://github.com/Ethan3600/magento2-CronjobManager/pull/78

I'm trying to find time to test it myself, but I intend to support Magento 2.3

**Comment by Ethan3600** [comment]
Aiming for magento 2.3 support in the upcoming release v1.6.4!

I'll close this out when I make the release

**Comment by Ethan3600** [comment]
Please upgrade to v1.6.4 for Magento 2.3 support. Going to close this out. If you run into any problems, please don't hesitate to create an issue.

Thanks for using the Cron Job Manager!

**Comment by peterjaap** [comment]
:+1: LGTM
