### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by itris** [Ethan3600/EthanYehuda_CronjobManager#80]
All current versions of this extension have this restraint; "php": "~7.0.0|~7.1.0",.

Do you have any idea when this extension will be PHP 7.2 compatible or maybe it is, but it hasn't been tested yet?

**Comment by Ethan3600** [comment]
Just needs to be tested.

**Comment by Ethan3600** [comment]
Please upgrade to v1.6.4 for support for PHP 7.2. Going to close this ticket out.

After testing, I found that all functionality seems to be working as expected, so I just updated composer.json.

If you have any problems please don't hesitate to create an issue.

Thanks for using the Cron Job Manager!
