### ISSUE TITLE
REST Api Integration Feature

### ISSUE THREAD

**Issue by Ethan3600** [Ethan3600/EthanYehuda_CronjobManager#83]
I'd like the Cron Job Manager to expose a REST Api so third parties can manipulate and keep track of the Crons in Magento.

Maybe even a GraphQl API?

**Comment by pmclain** [comment]
If you aren’t already planning to do this yourself, I’m up for assisting.

**Comment by Ethan3600** [comment]
That'd be pretty awesome @pmclain !

**Comment by pmclain** [comment]
@Ethan3600 Here's a first pass at the service contracts and API endpoints https://github.com/pmclain/magento2-CronjobManager/commit/942b7c84c49b0c40e0cdf7ccd625c6c6d7f81f79

The lack of [get|set]ters for data properties in `\Magento\Cron\Model\Schedule` means the class cannot be accepted or returned by Magento's API resolvers :(. To work around this, I added a data interface for `Schedule` and use two adapters for handling conversions between the core `Schedule` and the data interface. This looks and feels dirty but was the only solution I could think of that still allowed proper parameter validation for inbound webapi requests and proper self-documenting swagger. The alternative of using an associative array seemed dirtier than the adapters.

In the later versions `ScheduleManagementInterface` and `ScheduleRepositoryInterface` would replace usage of the current `Manager`. In the short term, the majority of the public methods in `Manager` could call the equivalent method in one of the two `Interfaces`. I've tinkered with this locally and the result looks something like this https://github.com/pmclain/magento2-CronjobManager/commit/95b41265865fff0ad2aaa78b246e19671e33d84a

Does this seem like a viable path?

**Comment by Ethan3600** [comment]
@pmclain this looks like a good plan. Just be cautious about nullable types. We still support PHP 7.0, so that'll break compatibility. Example: https://github.com/pmclain/magento2-CronjobManager/commit/942b7c84c49b0c40e0cdf7ccd625c6c6d7f81f79#diff-d6b799b972262a75352441f3573c37b5R25

I get that we're using adapters so that we can return an instance of `\EthanYehuda\CronjobManager\Api\Data\ScheduleInterface` instead of `\Magento\Cron\Model\Schedule`, but I don't think I get why.

Can you explain "Magento's API resolvers" a bit more? Specifically why they need those getters and setters? `\Magento\Cron\Model\Schedule` inherits from AbstractData so I'd assume "magic methods" are fair game, no? Sorry for the knowledge gap :disappointed: 

Other than that, I think everything makes sense!

**Comment by pmclain** [comment]
> We still support PHP 7.0.

But why? :) I'll update.

> Can you explain "Magento's API resolvers" a bit more?

Objects returned by the API are more or less the output of the object's public getters. Magento looks at an object with method `getScheduleId` and returns an object with the property `schedule_id`. These public methods are also parsed when generating the swagger documentation `http://<magento_host>/swagger`. `\Magento\Cron\Model\Schedule` does not explicitly define any getters, so the data is there but Magento doesn't know that when creating the request response.

**Comment by Ethan3600** [comment]
I'm a little hesitant since some people may still use PHP 7.0 for Magento 2.2 since Magento still supports it: https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#php

RE API: Ok, this makes sense! Funny how that works.

**Comment by Ethan3600** [comment]
Closing this issue. See #87
