### ISSUE TITLE
Duplicated cron jobs

### ISSUE THREAD

**Issue by jmpedrosa** [Ethan3600/EthanYehuda_CronjobManager#86]
Hi I'm running your extention over Magento 2.2.3 and the jobs schedules are being duplicated, check the scheduled date below.

![cronjobs](https://user-images.githubusercontent.com/8169003/50375162-c30c9500-05d7-11e9-9496-c36eddecd939.png)

In this particular case (sales_send_order_emails) I've modified the execution frecuency to every five minutes (*/5 * * * *)

 This issue is causing emails being send twice. What could I do to avoid this?

**Comment by Ethan3600** [comment]
Hi @jmpedrosa this seems like this is more likely a Magento bug. 

The dashboard only **displays** what's in the `cron_schedule` table. It doesn't edit or alter the scheduling mechanism. Do you have some steps to help me reproduce this?

Thanks for using the CJM!

**Comment by Ethan3600** [comment]
Going to close this out due to lack of response. Feel free to comment and I'll open the issue again!

**Comment by jmpedrosa** [comment]
> Going to close this out due to lack of response. Feel free to comment and I'll open the issue again!

Hi Ethan, sorry I didn't reply earlier. Yes, it turns out, this is a bug in magento. Thank you for your time!
