### ISSUE TITLE
After updating through composer not able to compile anymore

### ISSUE THREAD

**Issue by digikeijs** [Ethan3600/EthanYehuda_CronjobManager#89]
Parse error:  syntax error, unexpected '?' in /data/web/current/vendor/ethanyehuda/magento2-cronjobmanager/Model/ScheduleManagement.php on line 100

**Comment by Ethan3600** [comment]
Thank you @digikeijs for reporting this bug! We have resolved the issue in the [new release: v1.7.1](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v1.7.1)

Please upgrade to the latest version of the CJM.
