### ISSUE TITLE
cronmanager:runjob doesn't initialize using store 0

### ISSUE THREAD

**Issue by kyriog** [Ethan3600/EthanYehuda_CronjobManager#91]
**Describe the bug**
When a cron is run using `bin/magento cronmanager:runjob <cronjob>`, the cron starts as the first store view of the default website.
This is inconsistant with the default cron `bin/magento cron:run` which starts with the admin store view.

**To Reproduce**
1. Run any `bin/magento cronmanager:runjob <cronjob>` using xdebug
2. When execution reaches `Magento\Store\Model\StoreResolver::readStoresData()`:
   * `$this->runMode == "website"` and `$this->scopeCode == null`
   * Consequence: `Magento\Store\Model\StoreManager::$currentStoreId` is set to **1**.
   * (module entry point is `EthanYehuda\CronjobManager\Console\Command\Runjob::execute()` on first line)
3. Run `bin/magento cron:run` using xdebug
4. When execution reaches `Magento\Store\Model\StoreResolver::readStoresData()`:
   * `$this->runMode == "store"` and `$this->scopeCode == "admin"`
   * Consequence: `Magento\Store\Model\StoreManager::$currentStoreId` is set to **0**.

**Expected behavior**
Using `cronmanager:runjob` should be consistant with native magento cron.
This could (and does, in my case) cause issues when processing store-related things, like loading or saving products.

**Environment (please complete the following information):**
 - OS: Host macOS, magento running in Vagrant Ubuntu
 - Browser: Terminal
 - Cron Job Manager Version: v1.7.1 (commit 468c21921180d870ff3311be15c57fc92b28b26f)
 - Magento Version: 2.3.0
 - PHP Version: 7.2.13

**Additional context**
I'll continue to investigate this issue and hopefully propose a pull request when I'll found a solution if you're not faster than me.

**Comment by Ethan3600** [comment]
Hi @kyriog, thank you for using the CJM!

I wonder if switching the const [here](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Console/Command/Runjob.php#L67) to [this](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/App/Area.php#L22) will help.

Essentially making the "area" equal to "crontab." 

Can you try it out?

**Comment by kyriog** [comment]
Unfortunately, it doesn't work.

The reason of this is because `Magento\Store\Model\StoreManager::$currentStoreId` is set by the `getStore()` method, which is called by Runjob first method, `$this->managerFactory->create()`.

I've tried to move the `setAreaCode()` on top of the execution,  but the store ID is still set to 1 when the managerFactory is used.

I continue my investigations.

**Comment by kyriog** [comment]
I've just found [this odd passage](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Cron/Console/Command/CronCommand.php#L97-L100) in M2 source code:
```php
$omParams = $_SERVER;
$omParams[StoreManager::PARAM_RUN_CODE] = 'admin';
$omParams[Store::CUSTOM_ENTRY_POINT_PARAM] = true;
$objectManager = $this->objectManagerFactory->create($omParams);
```

I've tried to apply these parameters to `managerFactory` new object instantiation, and this time current store ID is correctly set to 0.

I'll investigate if there could have any side effect with the `DateTimeFactory`.

I'm not a big fan of such an ugly solution, but as it's come from core, I'll just check if we can replace the `admin` literal string by a constant and submit a PR if I don't see any problem.

**Comment by kyriog** [comment]
Okay, let me try to explain what I've found.

Firstly, I investigate on where does the `$this->runMode` and `$this->scopeCode` came from.
It seems they're set directly in `Magento\Store\Model\StoreResolver` dependency injection:
```php
public function __construct(
        […]
        $runMode = ScopeInterface::SCOPE_STORE,
        $scopeCode = null
    ) {
        […]
        $this->runMode = $scopeCode ? $runMode : ScopeInterface::SCOPE_WEBSITE;
        $this->scopeCode = $scopeCode;
    }
```

I analyzed this point from the core cron command view. This object is instantiated twice:
* First with `$runMode = "store"` and `$scopeCode = null` which come from the `ObjectManager` instantiation, which is called directly from the Console CLI framework.
* Second with `$runMode = "store"` and `$scopeCode = "admin"` which come from `Magento\Framework\App\Cron::launch()` (which is run from the `CronCommand::execute()`)

From what I understood, this second instantiation is possible because of `ObjectManager` manual instantiation from `CronCommand::execute()`:
```php
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        […]
        $omParams = $_SERVER;
        $omParams[StoreManager::PARAM_RUN_CODE] = 'admin';
        $omParams[Store::CUSTOM_ENTRY_POINT_PARAM] = true;
        $objectManager = $this->objectManagerFactory->create($omParams);
        […]
        $cronObserver = $objectManager->create(\Magento\Framework\App\Cron::class, ['parameters' => $params]);
        $cronObserver->launch();
        […]
    }
```

I find this is a pretty ugly solution, but from my first tests, this seems to work with CJM.
I'll clean my dev a bit and submit a PR.
