### ISSUE TITLE
Doesn't work at 2.2.7

### ISSUE THREAD

**Issue by GraysonChiang** [Ethan3600/EthanYehuda_CronjobManager#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Cron Job Manager Version [e.g. 1.6.4]
 - Magento Version [e.g. 2.3.0]
 - PHP Version [e.g. 7.0.33]

**Additional context**

**Comment by Ethan3600** [comment]
Hi @GraysonChiang, thank you for using the CJM.

What specifically doesn't work?
Are there any error messages? How can I reproduce this issue?

Can you please follow the instructions of the bug template? Saying something "doesn't work" isn't helpful.

I'm going to close this ticket. Please create a new one with the necessary details provided by the template, or a clear set of instructions on how to reproduce the issue.
