### ISSUE TITLE
Cronjob process monitoring

### ISSUE THREAD

**Issue by schmengler** [Ethan3600/EthanYehuda_CronjobManager#95]
**Is your feature request related to a problem? Please describe.**
I want to see if a "running" cronjob is actually still running or has crashed

**Describe the solution you'd like**
- Show process id in grid
- Regularly check if processes are still running, show "last seen" timestamp in grid
- Add "kill" action

**Comment by schmengler** [comment]
Working on it!

**Comment by schmengler** [comment]
Apparently the following was already implemented
- save pid when starting job
- set jobs to "error" if they are "running" but process went away

Still missing:
- Information in the grid: pid, "last seen" (probably not necessary because if it's not seen anymore, status is set to "error")
- "kill" action, e.g. for cronjobs that went into an endless loop

**Comment by Ethan3600** [comment]
@schmengler Thank you for opening this issue (and the other ones too!). I'll admit, I struggled on how to implement those two missing features without overriding the ProcessCronQueueObserver. My biggest fear was that we'll need to have code like this to compensate for API changes in core Magento (as Magento continues to grow):

```php
if (magento_version = 2.{{ flll in the blank }} ) { 
    // some logic 
} else if ( anther magento version) {
    ...
}
```

Maintaining the CJM will be a nightmare if we start overriding core Magento functions.

**Comment by schmengler** [comment]
@Ethan3600 Totally agree, that's also what I disliked about similar modules. Pull request is coming, no overrides!

**Comment by schmengler** [comment]
Further possible improvements:
- add "kill_request" column to grid (can be turned off by default) to show when a process kill has been requested
- improved error messages, e.g. when trying to kill a process that is not running
- Try to send SIGINT and wait if it succeeds before sending SIGKILL (as in https://github.com/AOEpeople/Aoe_Scheduler/blob/b1ea97c87dc9e18d3135768e551a4486fbc1b399/app/code/community/Aoe/Scheduler/Model/Schedule.php#L483-L513)
