### ISSUE TITLE
Make sure to kill processes only on the same host

### ISSUE THREAD

**Issue by schmengler** [Ethan3600/EthanYehuda_CronjobManager#98]
**Is your feature request related to a problem? Please describe.**
If cron jobs are distributed on several servers, e.g. by cron group, the check for dead processes can return false positives, resulting in "Process went away" messages.

**Describe the solution you'd like**
Save the hostname together with the pid and filter by pid and hostname. The feature should be optional, because it may cause different issues if the hostname changes during deployments.

**Comment by aligent-lturner** [comment]
This is a big issue on Magento cloud, where cron jobs are distributed across servers and you have no control over which one the job is run on (and which one is queried later).

An alternative would be to use the option that disables the check, but then you run the risk of blockages.
